[package]
name = "laurel_common"
version = "0.1.0"
edition = "2024"

[dependencies]
iced.workspace = true

async-lsp.workspace = true
tree-sitter.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
